# Generated by Django 4.2.16 on 2026-08-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
