# Generated by Django 4.2.16 on 2026-08-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
