# Generated by Django 4.2.16 on 2026-08-26 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portfolio', '0003_portfolio_email_portfolio_github_portfolio_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_url', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
